### ISSUE TITLE
Allow vamp-ir to be used as a library

### ISSUE THREAD

**Issue by lopeetall** [anoma/vamp-ir#57]
Both the Juvix team and Taiga team have expressed interest in this

**Comment by jonaprieto** [comment]
Which commit closed this issue?

**Comment by lopeetall** [comment]
This one:

https://github.com/anoma/vamp-ir/commit/bdbac967bb8d7f56cbf06f042fa2ce6123d5b551

But then the library didn't compile for some users due to some dependency updates, but that issue was fixed in this PR from yesterday: 

https://github.com/anoma/vamp-ir/commit/72ec820a1d6788f8618e2ca1e799b9a358709a83

**Comment by jonaprieto** [comment]
Thanks!
