### ISSUE TITLE
Writing our first Vamp-IR examples

### ISSUE THREAD

**Issue by simonmasson** [anoma/vamp-ir#7]
As far as I understand, the goal of Vamp-IR is to be able to use complicated circuits in a simple way. I would like to have a practical example with a "complicated" circuit. For example, we can consider a hash function circuit, very useful for ZK proofs applications. Depending on your curve system, you can use [Poseidon](https://www.poseidon-hash.info/) over:
* the scalar field of `bls12_381` using ZK-Garage [implementation](https://github.com/ZK-Garage/plonk/tree/poseidon_hash/plonk-hashing/src/poseidon),
* the scalar field of `vesta` using Zcash [implementation](https://github.com/zcash/halo2/tree/main/halo2_gadgets/src/poseidon). 

The circuit can be designed differently depending on the implementation. For example it could either compute the hash and output it as a variable, either (given `input` and `output`) check that `output` is the hash of `input`. Using Vamp-IR, the user doesn't care about this implementation detail and is able to create the circuit in a simple way like:
```
// this is vamp-ir code
output = Poseidon(input)
```
(somewhere, the user needs to decide on the backend: Zcash or ZK-Garage)

My questions:
1. Can we already do this kind of example with Vamp-IR?
2. What is needed to achieve this example?
3. Do we need Juvix at some point for this?

**Comment by CarloModicaPortfolio** [comment]
Hi, there is now a balke2s hash in the repo, that can be used as a Vamp-IR example
